name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Adjust this to match your main branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0  # Make sure to use the latest version
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
# change policy 7
    - name: Build Container Image
      run: gcloud builds submit --tag gcr.io/$PROJECT_ID/my-service:$GITHUB_SHA --verbosity=debug
    
    - name: Deploy to Cloud Run
      run: gcloud run deploy my-service --image gcr.io/$PROJECT_ID/my-service:$GITHUB_SHA --region us-central1 --allow-unauthenticated --platform managed --verbosity=debug

